name: Movie Cover

on:
  workflow_dispatch:
  schedule:
    - cron: "1 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.0'
    - name: Create local changes
      run: |
        cd .github/script
        pip install -r requirements.txt
        python generate_readme.py
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Updated movie cover on letterboxed $(date +%Y-%m-%d)" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
